version: '3.4'

networks:
  backend:
  frontend:

services:
  customerdb:
    container_name: customer-db
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backend
    ports:
      - 18001:3306

  customerwebapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: CustomerWebAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=customerdb
      - DB_NAME=dms_customer
      - DB_ROOT_PASSWORD=password

  productdb:
    container_name: product-db
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 18003:3306
    networks:
      - backend

  productwebapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: ProductWebAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=productdb
      - DB_NAME=dms_product
      - DB_ROOT_PASSWORD=password

  orderdb:
    container_name: order-db
    image: mongo
    ports:
      - 18005:27017
    networks:
      - backend

  orderwebapi:
    container_name: order-api
    image: ${DOCKER_REGISTRY-}orderwebapi
    build:
      context: .
      dockerfile: OrderWebAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=orderdb
      - DB_NAME=dms_order

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 8001:80
    networks:
      - backend
      - frontend

  blazorwebserverui:
    container_name: blazor-web-ui
    image: ${DOCKER_REGISTRY-}blazorwebserverui
    build:
      context: .
      dockerfile: BlazorWebServerUI/Dockerfile
    ports:
      - 8002:80
    networks:
      - frontend